source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

$podName = 'MobileMessaging'

target 'MobileMessagingExample' do
    pod $podName, :path => '../'
end

target 'MobileMessagingExample_Tests' do
    pod $podName, :path => '../'
end

system 'mkdir -p "./Pods/MobileMessaging/Pod/Classes/Vendor/AFNetworking/"'
system 'cp "../Pod/Classes/Vendor/AFNetworking/module.private.modulemap" "./Pods/MobileMessaging/Pod/Classes/Vendor/AFNetworking/module.private.modulemap"'
