source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'MobileChatExample' do
	pod 'MobileMessaging', :path => '../'
	pod 'MobileMessaging/MobileChat', :path => '../'
end