source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '15.0'

target 'MobileChatExample' do
	pod 'MobileMessaging', :path => '../'
	pod 'MobileMessaging/InAppChat', :path => '../'
  	pod 'MobileMessaging/WebRTCUI', :path => '../'
	pod 'SwiftJWT', '~> 3.6.1' 

    target 'MobileMessagingNotificationExtension' do
        inherit! :search_paths
    end
end

# Fix Xcode 14 resource bundle signing issues
# https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1259231655
post_install do |installer|
  installer.pods_project.targets.each do |target|
    shell_script_path = "Pods/Target Support Files/#{target.name}/#{target.name}-frameworks.sh"
    if File::exists?(shell_script_path)
      shell_script_input_lines = File.readlines(shell_script_path)
      shell_script_output_lines = shell_script_input_lines.map { |line| line.sub("source=\"$(readlink \"${source}\")\"", "source=\"$(readlink -f \"${source}\")\"") }
      File.open(shell_script_path, 'w') do |f|
        shell_script_output_lines.each do |line|
          f.write line
        end
      end
    end
#    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
	config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'

	# Fix for Xcode 15 issue, to be solved by cocoapods 1.13.
    	xcconfig_path = config.base_configuration_reference.real_path
    	xcconfig = File.read(xcconfig_path)
    	xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
    	File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
	# End of Xcode 15 issue fix

      end
#    end
  end
end
