source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '12.0'

target 'InboxExample' do
	pod 'MobileMessaging', :path => '../'
	pod 'MobileMessaging/Inbox', :path => '../'
end
