source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '12.0'

target 'InboxExample' do
	pod 'MobileMessaging', :path => '../'
	pod 'MobileMessaging/Inbox', :path => '../'
end

# Fix Xcode 14 resource bundle signing issues
# https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1259231655
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
