source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'

$podName = 'MobileMessaging'
$chatPodName = 'MobileMessaging/InAppChat'
$inboxPodName = 'MobileMessaging/Inbox'

def includeMobileMessagingPods
	pod $podName, :path => '../'
	pod $chatPodName, :path => '../'
	pod $inboxPodName, :path => '../'
end

target 'MobileMessagingExample_static' do
  includeMobileMessagingPods
  pod 'SwiftJWT'
end

target 'NotificationServiceExtension' do
	pod 'MobileMessagingNotificationExtension', :path => '../'
end

target 'MobileMessagingExample_static_Tests' do
  pod 'SwiftJWT'
  includeMobileMessagingPods
end

target 'MobileMessagingExample_static_Tests_Device' do
  pod 'SwiftJWT'
	includeMobileMessagingPods
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
			if target.name == 'MobileMessaging'
				config.build_settings['ENABLE_TESTABILITY'] = 'YES' # for this particular project we want the SDK to be testable
				config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
			end
		end
	end
end
