#!/bin/bash
set -e

# Skip if on master branch
if [ "$BRANCH_NAME_TO_BUILD" = "master" ]; then
  echo "================================================"
  echo "Skipping Copyright Header Check (master branch)"
  echo "================================================"
  exit 0
fi

echo "================================================"
echo "Running Copyright Header Check"
echo "================================================"

# Define project configurations: "PROJECT_NAME ROOT_PATH"
declare -a PROJECTS=(
  "MobileMessaging ."
  "MobileChatExample ChatExample"
  "ChatSwiftUIDemo ChatSwiftUIDemo"
  "MobileMessagingExample Example"
  "MobileMessagingExample Example_SPM"
  "MobileMessagingExample Example_static"
  "InboxExample InboxExample"
)

# Run the copyright header script for each project
for project_config in "${PROJECTS[@]}"; do
  # Split the configuration into project name and root path
  read -r project_name root_path <<< "$project_config"

  echo ""
  echo "Processing: $project_name (in $root_path)"
  echo "----------------------------------------"

  ./Scripts/add-copyright-header.sh "$project_name" "$root_path"
done

echo ""
echo "================================================"
echo "Copyright Header Check Complete"
echo "================================================"

# Check if any files were modified
if git diff --exit-code --quiet; then
  echo "✅ All files have proper copyright headers"
  exit 0
else
  echo "⚠️  Files with missing copyright headers were detected and fixed"

  # Show which files were modified
  echo ""
  echo "Modified files:"
  git diff --name-only

  # Commit the changes
  git add -A
  git commit -m "Add missing copyright headers

Automatically generated by Jenkins CI"

  # Disable any existing credential helpers (prevents keychain storage)
  git config --local --unset-all credential.helper || true

  # Setup temporary credential helper that only provides credentials, never stores
  git config --local credential.helper '!f() { test "$1" = get && echo "username=${GIT_USERNAME}" && echo "password=${GIT_PASSWORD}"; }; f'

  git push origin HEAD:${BRANCH_NAME_TO_BUILD}

  echo ""
  echo "✅ Changes committed and pushed to branch"
  echo ""
  echo "❌ BUILD FAILED: Copyright headers were missing"
  echo "   A commit has been created with the fixes."
  echo "   Please pull the latest changes."

  # Exit with failure to mark the build as failed
  exit 1
fi
