//
//  ChatBEPO.swift
//  MobileMessaging
//
// Copyright (c) 2016-2026 Infobip Limited
// Licensed under the Apache License, Version 2.0
//

extension UIColor {
    convenience init(mmHex: String, alpha: CGFloat = 1.0) {
        var hexSanitized = mmHex.trimmingCharacters(in: .whitespacesAndNewlines)
        hexSanitized = hexSanitized.replacingOccurrences(of: "#", with: "")

        var rgb: UInt64 = 0

        Scanner(string: hexSanitized).scanHexInt64(&rgb)

        var red = CGFloat.zero
        var green = CGFloat.zero
        var blue = CGFloat.zero
        var alphaH = alpha

        if hexSanitized.count == 6 {
            red = CGFloat((rgb & 0xFF0000) >> 16) / 255.0
            green = CGFloat((rgb & 0x00FF00) >> 8) / 255.0
            blue = CGFloat(rgb & 0x0000FF) / 255.0
        } else if hexSanitized.count == 8 {
            red = CGFloat((rgb & 0xFF000000) >> 32) / 255.0
            green = CGFloat((rgb & 0x00FF0000) >> 16) / 255.0
            blue = CGFloat((rgb & 0x0000FF00) >> 8) / 255.0
            alphaH = CGFloat(rgb & 0x000000FF) / 255.0
        }
        self.init(red: red, green: green, blue: blue, alpha: alphaH)
    }
}

public struct MMChatBEPO {
    public static let colorTextPrimary = UIColor(mmHex: "#1b1b1a")
    public static let colorTextSecondary = UIColor(mmHex: "#545452")
    public static let colorTextTertiary = UIColor(mmHex: "#72716F")
    public static let colorTextSubdued = UIColor(mmHex: "#a6a5a2")
    public static let colorTextDisabled = UIColor(mmHex: "#c4c4c2")
    public static let colorTextContrast = UIColor(mmHex: "#ffffff")
    public static let colorTextAccent = UIColor(mmHex: "#fc6423")
    public static let colorTextSelection = UIColor(mmHex: "#1b1b1a")
    public static let colorTextPrimaryInverse = UIColor(mmHex: "#ffffff")
    public static let colorTextSecondaryInverse = UIColor(mmHex: "#ffffffcc")
    public static let colorTextTertiaryInverse = UIColor(mmHex: "#ffffff99")
    public static let colorTextSubduedInverse = UIColor(mmHex: "#ffffff66")
    public static let colorTextDisabledInverse = UIColor(mmHex: "#ffffff40")
    public static let colorTextInfo = UIColor(mmHex: "#3950ad")
    public static let colorTextSuccess = UIColor(mmHex: "#247058")
    public static let colorTextWarning = UIColor(mmHex: "#85540a")
    public static let colorTextDanger = UIColor(mmHex: "#ab1628")
    public static let colorTextInfoInverse = UIColor(mmHex: "#879bd6")
    public static let colorTextSuccessInverse = UIColor(mmHex: "#41ba8a")
    public static let colorTextWarningInverse = UIColor(mmHex: "#ffbc1f")
    public static let colorTextDangerInverse = UIColor(mmHex: "#f06979")
    public static let colorLink = UIColor(mmHex: "#2e7899")
    public static let colorLinkHover = UIColor(mmHex: "#0d516e")
    public static let colorLinkActive = UIColor(mmHex: "#074058")
    public static let colorLinkDisabled = UIColor(mmHex: "#c4c4c2")
    public static let colorLinkStrong = UIColor(mmHex: "#1b1b1a")
    public static let colorLinkStrongHover = UIColor(mmHex: "#545452")
    public static let colorLinkStrongActive = UIColor(mmHex: "#3b3b39")
    public static let colorLinkInverse = UIColor(mmHex: "#ffffff")
    public static let colorLinkHoverInverse = UIColor(mmHex: "#ffffffb3")
    public static let colorLinkActiveInverse = UIColor(mmHex: "#ffffffe6")
    public static let colorLinkDisabledInverse = UIColor(mmHex: "#ffffff40")
    public static let colorIcon = UIColor(mmHex: "#545452")
    public static let colorIconHover = UIColor(mmHex: "#3b3b39")
    public static let colorIconActive = UIColor(mmHex: "#1b1b1a")
    public static let colorIconDisabled = UIColor(mmHex: "#c4c4c2")
    public static let colorIconContrast = UIColor(mmHex: "#ffffff")
    public static let colorIconAccent = UIColor(mmHex: "#fc6423")
    public static let colorIconAccentSubdued = UIColor(mmHex: "#fff5eb")
    public static let colorIconInverse = UIColor(mmHex: "#ffffffcc")
    public static let colorIconHoverInverse = UIColor(mmHex: "#ffffffe6")
    public static let colorIconActiveInverse = UIColor(mmHex: "#ffffff")
    public static let colorIconDisabledInverse = UIColor(mmHex: "#ffffff40")
    public static let colorIconInfo = UIColor(mmHex: "#3950ad")
    public static let colorIconSuccess = UIColor(mmHex: "#208560")
    public static let colorIconWarning = UIColor(mmHex: "#ad7410")
    public static let colorIconDanger = UIColor(mmHex: "#cf182e")
    public static let colorIconInfoInverse = UIColor(mmHex: "#879bd6")
    public static let colorIconSuccessInverse = UIColor(mmHex: "#41ba8a")
    public static let colorIconWarningInverse = UIColor(mmHex: "#ffbc1f")
    public static let colorIconDangerInverse = UIColor(mmHex: "#e84154")
    public static let colorBackgroundPrimary = UIColor(mmHex: "#ffffff")
    public static let colorBackgroundSecondary = UIColor(mmHex: "#f4f4f2")
    public static let colorBackgroundTertiary = UIColor(mmHex: "#e5e5e3")
    public static let colorBackgroundModerate = UIColor(mmHex: "#c4c4c2")
    public static let colorBackgroundContrast = UIColor(mmHex: "#1b1b1a")
    public static let colorBackgroundAccent = UIColor(mmHex: "#fc6423")
    public static let colorBackgroundAccentSubdued = UIColor(mmHex: "#fff5eb")
    public static let colorBackgroundOverlay = UIColor(mmHex: "#1b1b1acc")
    public static let colorBackgroundOverlaySubdued = UIColor(mmHex: "#1b1b1a7a")
    public static let colorBackgroundSelection = UIColor(mmHex: "#beddeb")
    public static let colorBackgroundPrimaryInverse = UIColor(mmHex: "#3b3b39")
    public static let colorBackgroundSecondaryInverse = UIColor(mmHex: "#ffffff1a")
    public static let colorBackgroundTertiaryInverse = UIColor(mmHex: "#ffffff33")
    public static let colorBackgroundModerateInverse = UIColor(mmHex: "#ffffff4d")
    public static let colorBackgroundInteractive = UIColor(mmHex: "#2e7899")
    public static let colorBackgroundInteractiveHover = UIColor(mmHex: "#0d516e")
    public static let colorBackgroundInteractiveActive = UIColor(mmHex: "#074058")
    public static let colorBackgroundInteractiveDragged = UIColor(mmHex: "#f0f9fc")
    public static let colorBackgroundInteractiveDisabled = UIColor(mmHex: "#c4c4c2")
    public static let colorBackgroundInteractiveInverse = UIColor(mmHex: "#ffffff")
    public static let colorBackgroundInteractiveSubdued = UIColor(mmHex: "#72716F")
    public static let colorBackgroundInteractiveSubduedHover = UIColor(mmHex: "#545452")
    public static let colorBackgroundInteractiveSubduedDisabled = UIColor(mmHex: "#d9d8d7")
    public static let colorBackgroundInfo = UIColor(mmHex: "#3950ad")
    public static let colorBackgroundInfoModerate = UIColor(mmHex: "#b9c7eb")
    public static let colorBackgroundInfoSubdued = UIColor(mmHex: "#e8efff")
    public static let colorBackgroundWarning = UIColor(mmHex: "#d69616")
    public static let colorBackgroundWarningModerate = UIColor(mmHex: "#ffefc2")
    public static let colorBackgroundWarningSubdued = UIColor(mmHex: "#fff8e3")
    public static let colorBackgroundDanger = UIColor(mmHex: "#cf182e")
    public static let colorBackgroundDangerModerate = UIColor(mmHex: "#facfd4")
    public static let colorBackgroundDangerSubdued = UIColor(mmHex: "#fff0f1")
    public static let colorBackgroundSuccessStrong = UIColor(mmHex: "#247058")
    public static let colorBackgroundSuccess = UIColor(mmHex: "#208560")
    public static let colorBackgroundSuccessModerate = UIColor(mmHex: "#a6e0c9")
    public static let colorBackgroundSuccessSubdued = UIColor(mmHex: "#ebf5f1")
    public static let colorBorderPrimary = UIColor(mmHex: "#d9d8d7")
    public static let colorBorderSecondary = UIColor(mmHex: "#a6a5a2")
    public static let colorBorderTertiary = UIColor(mmHex: "#ffffff")
    public static let colorBorderFocus = UIColor(mmHex: "#5d72c2")
    public static let colorBorderAccent = UIColor(mmHex: "#fc6423")
    public static let colorBorderAccentSubdued = UIColor(mmHex: "#ffe4cc")
    public static let colorBorderPrimaryInverse = UIColor(mmHex: "#ffffff4d")
    public static let colorBorderFocusInverse = UIColor(mmHex: "#ffffffb3")
    public static let colorBorderInteractive = UIColor(mmHex: "#2e7899")
    public static let colorBorderInteractiveHover = UIColor(mmHex: "#0d516e")
    public static let colorBorderInteractiveActive = UIColor(mmHex: "#074058")
    public static let colorBorderInteractiveDisabled = UIColor(mmHex: "#c4c4c2")
    public static let colorBorderInteractiveSubdued = UIColor(mmHex: "#72716F")
    public static let colorBorderInteractiveSubduedHover = UIColor(mmHex: "#3b3b39")
    public static let colorBorderInteractiveSubduedDisabled = UIColor(mmHex: "#d9d8d7")
    public static let colorBorderInteractiveSubduedInverse = UIColor(mmHex: "#ffffff66")
    public static let colorBorderInteractiveSubduedHoverInverse = UIColor(mmHex: "#ffffffb3")
    public static let colorBorderInteractiveSubduedDisabledInverse = UIColor(mmHex: "#ffffff26")
    public static let colorBorderInfoStrong = UIColor(mmHex: "#051f66")
    public static let colorBorderInfo = UIColor(mmHex: "#3950ad")
    public static let colorBorderInfoSubdued = UIColor(mmHex: "#b9c7eb")
    public static let colorBorderSuccessStrong = UIColor(mmHex: "#224741")
    public static let colorBorderSuccess = UIColor(mmHex: "#208560")
    public static let colorBorderSuccessSubdued = UIColor(mmHex: "#b6d1c6")
    public static let colorBorderWarningStrong = UIColor(mmHex: "#85540a")
    public static let colorBorderWarning = UIColor(mmHex: "#d69616")
    public static let colorBorderWarningSubdued = UIColor(mmHex: "#ffe299")
    public static let colorBorderDangerStrong = UIColor(mmHex: "#871321")
    public static let colorBorderDanger = UIColor(mmHex: "#cf182e")
    public static let colorBorderDangerSubdued = UIColor(mmHex: "#facfd4")
    public static let colorBorderSuccessStrongInverse = UIColor(mmHex: "#6dcfa7")
    public static let colorBorderSuccessInverse = UIColor(mmHex: "#1ca66f")
    public static let colorBorderInfoStrongInverse = UIColor(mmHex: "#879bd6")
    public static let colorBorderInfoInverse = UIColor(mmHex: "#5d72c2")
    public static let colorBorderWarningStrongInverse = UIColor(mmHex: "#ffc847")
    public static let colorBorderWarningInverse = UIColor(mmHex: "#d69616")
    public static let colorBorderDangerStrongInverse = UIColor(mmHex: "#f06979")
    public static let colorBorderDangerInverse = UIColor(mmHex: "#e84154")
    public static let colorButtonPrimary = UIColor(mmHex: "#ffffff")
    public static let colorButtonPrimaryDisabled = UIColor(mmHex: "#c4c4c2")
    public static let colorButtonBackgroundPrimary = UIColor(mmHex: "#2e7899")
    public static let colorButtonBackgroundPrimaryHover = UIColor(mmHex: "#0d516e")
    public static let colorButtonBackgroundPrimaryActive = UIColor(mmHex: "#074058")
    public static let colorButtonBackgroundPrimaryDisabled = UIColor(mmHex: "#f4f4f2")
    public static let colorButtonSecondary = UIColor(mmHex: "#2e7899")
    public static let colorButtonSecondaryHover = UIColor(mmHex: "#0d516e")
    public static let colorButtonSecondaryActive = UIColor(mmHex: "#074058")
    public static let colorButtonSecondaryDisabled = UIColor(mmHex: "#c4c4c2")
    public static let colorButtonSecondaryInverse = UIColor(mmHex: "#ffffff")
    public static let colorButtonSecondaryDisabledInverse = UIColor(mmHex: "#ffffff40")
    public static let colorButtonBackgroundSecondary = UIColor(mmHex: "#ffffff")
    public static let colorButtonBackgroundSecondaryHover = UIColor(mmHex: "#f0f9fc")
    public static let colorButtonBackgroundSecondaryActive = UIColor(mmHex: "#beddeb")
    public static let colorButtonBackgroundSecondaryDisabled = UIColor(mmHex: "#ffffff")
    public static let colorButtonBackgroundSecondaryHoverInverse = UIColor(mmHex: "#ffffff1a")
    public static let colorButtonBackgroundSecondaryActiveInverse = UIColor(mmHex: "#ffffff33")
    public static let colorButtonBorderSecondary = UIColor(mmHex: "#2e7899")
    public static let colorButtonBorderSecondaryHover = UIColor(mmHex: "#0d516e")
    public static let colorButtonBorderSecondaryActive = UIColor(mmHex: "#074058")
    public static let colorButtonBorderSecondaryDisabled = UIColor(mmHex: "#c4c4c2")
    public static let colorButtonBorderSecondaryInverse = UIColor(mmHex: "#ffffff")
    public static let colorButtonBorderSecondaryDisabledInverse = UIColor(mmHex: "#ffffff40")
    public static let colorButtonTertiary = UIColor(mmHex: "#2e7899")
    public static let colorButtonTertiaryHover = UIColor(mmHex: "#0d516e")
    public static let colorButtonTertiaryActive = UIColor(mmHex: "#074058")
    public static let colorButtonTertiaryDisabled = UIColor(mmHex: "#c4c4c2")
    public static let colorButtonBackgroundTertiary = UIColor(mmHex: "#ffffff00")
    public static let colorButtonBackgroundTertiaryHover = UIColor(mmHex: "#e5e5e3")
    public static let colorButtonBackgroundTertiaryActive = UIColor(mmHex: "#e5e5e3")
    public static let colorButtonBackgroundTertiaryDisabled = UIColor(mmHex: "#ffffff00")
    public static let colorButtonAccent = UIColor(mmHex: "#ffffff")
    public static let colorButtonAccentDisabled = UIColor(mmHex: "#c4c4c2")
    public static let colorButtonBackgroundAccent = UIColor(mmHex: "#fc6423")
    public static let colorButtonBackgroundAccentHover = UIColor(mmHex: "#d1521c")
    public static let colorButtonBackgroundAccentActive = UIColor(mmHex: "#ab4316")
    public static let colorButtonBackgroundAccentDisabled = UIColor(mmHex: "#f4f4f2")
    public static let colorButtonSuccess = UIColor(mmHex: "#ffffff")
    public static let colorButtonSuccessDisabled = UIColor(mmHex: "#c4c4c2")
    public static let colorButtonBackgroundSuccess = UIColor(mmHex: "#208560")
    public static let colorButtonBackgroundSuccessHover = UIColor(mmHex: "#195e4d")
    public static let colorButtonBackgroundSuccessActive = UIColor(mmHex: "#224741")
    public static let colorButtonBackgroundSuccessDisabled = UIColor(mmHex: "#f4f4f2")
    public static let colorButtonDanger = UIColor(mmHex: "#ffffff")
    public static let colorButtonDangerDisabled = UIColor(mmHex: "#c4c4c2")
    public static let colorButtonBackgroundDanger = UIColor(mmHex: "#cf182e")
    public static let colorButtonBackgroundDangerHover = UIColor(mmHex: "#ab1628")
    public static let colorButtonBackgroundDangerActive = UIColor(mmHex: "#871321")
    public static let colorButtonBackgroundDangerDisabled = UIColor(mmHex: "#f4f4f2")
    public static let colorOverflowScroll = UIColor(mmHex: "#72716fcc")
    public static let colorOverflowScrollInverse = UIColor(mmHex: "#ffffff40")
}
